#==============================
# General Site Config
#==============================
title: Code and Food
email: jeesunikim@gmail.com
description: Frontend Engineer Jeesun's blog on code and food
baseurl: ""
url: "https://www.codeandfood.com" # the base hostname & protocol for your site
twitter_username: codeandfood
github_username:  jeesunikim

# Build settings
markdown: kramdown
kramdown:
 input: GFM
highlighter: rouge

#==============================
# File inclusions/exclusions
#==============================
include: [".htaccess"]
exclude: ["node_modules", "Gemfile", "Gemfile.lock"]

#==============================
# Outputting
#==============================
# permalink: /:categories/:title
